# bot 配置文件，用于配置 bot 的相关信息，如协议、主机地址、端口号、访问令牌等。
bot:
  protocol: "ws"  # 协议 ws/wss
  host: "192.168.101.29"  # 主机地址
  port: 3001  # 端口号
  accessToken: "fenglin666"  # 访问令牌
  throwPromise: true
  reconnection: # 重连配置
    enabled: true
    attempts: 10
    delay: 5000
cmd:
 prefix: "#" # 命令前缀
